# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - run:
          name: Installing SUDO
          command: >-
            apt-get update && apt-get install -y sudo && rm -rf
            /var/lib/apt/lists/*
      - run:
          name: Installing GCC
          command: apt-get update && apt-get install -y g++

      - run:
          name: Install CMAKE
          command: apt-get update && apt-get install -y cmake

      - run:
          name: Install git
          command: apt-get update && apt-get install -y git

      - run:
          name: Create Build Files
          command: apt-get update && apt-get install -y libopenblas-dev

      - run:
          name: Create Build Files
          command: |-
            mkdir ./cmake-build-release
            cmake --DC_BUILD_TYPE=Release ./cmake-build-release/

      - run:
          name: Create Baseline
          command: make --directory=./cmake-build-release/ LBL_Test


